# Generated by Django 4.1.5 on 2023-01-30 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255, verbose_name='Nom')),
                ('lastName', models.CharField(max_length=255, verbose_name='Prenom')),
                ('address', models.CharField(max_length=255, verbose_name='Residence')),
                ('tel', models.CharField(max_length=10, unique=True, verbose_name='Numero De Telephone')),
                ('hashed', models.CharField(max_length=255, verbose_name='HASH')),
            ],
            options={
                'ordering': ['lastName', 'firstName'],
            },
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmprunt', models.DateTimeField()),
                ('status', models.CharField(choices=[('p', 'Present(e)'), ('a', 'Absent(e)')], default='n', help_text="la disponibilté de l'employé(e)", max_length=1)),
                ('idEmploye', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.employe')),
            ],
            options={
                'ordering': ['dateEmprunt'],
            },
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
