# Generated by Django 4.1.5 on 2023-01-30 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employe_pointage_delete_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='dateEmprunt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
